### ISSUE TITLE
Bitmagic documentation / implementation bug

### ISSUE THREAD

**Issue by ecurtz** [jsm174/wpc-emu-cs#1]
The comment on findMsbBit() doesn't actually match the return value or the original javascript, and in fact the example in the comment won't work with the example input.

Alternate super basic versions.

```
        // in: 0x0a, out: 0x04
        public static byte findMsbBit(byte uint8Value)
        {
            if ((uint8Value & 0x80) != 0) return 8;
            if ((uint8Value & 0x40) != 0) return 7;
            if ((uint8Value & 0x20) != 0) return 6;
            if ((uint8Value & 0x10) != 0) return 5;
            if ((uint8Value & 0x08) != 0) return 4;
            if ((uint8Value & 0x04) != 0) return 3;
            if ((uint8Value & 0x02) != 0) return 2;
            if ((uint8Value & 0x01) != 0) return 1;

            return 0;
        }
```

```
        // in: 5, out: 0x20
        public static byte setMsbBit(byte uint8Value = 0)
        {
            if (uint8Value >= 8) return 0;

            return (byte)(0x01 << uint8Value);
        }
```

**Comment by jsm174** [comment]
Thanks. I really don't want to deviate from the original javascript as it's been helpful for doing the line by line conversion and especially when doing comparisons. 

Can you post this over at [wpc-emu](https://github.com/neophob/wpc-emu) and I'll port whatever @neophob decides to do?

Just curious

> doesn't actually match the return value or the original javascript

the C# does seem to match the javascript. What am I missing? 

https://github.com/neophob/wpc-emu/blob/master/lib/boards/elements/bitmagic.js#L10

vs

https://github.com/jsm174/wpc-emu-cs/blob/master/src/WPCEmu/Boards/Elements/Bitmagic.cs#L10

**Comment by ecurtz** [comment]
// in: 0x0a, out: 0x08

The lookup version will return 0 for 0x0a, since it's not in the array, and the intent from what I can tell is it would return 4 (the bit index) versus 0x08 (the high bit value) if it did work for 0x0a. I'll submit the issue on the JS version though, good call.

**Comment by neophob** [comment]
@jsm174 take a look at https://github.com/neophob/wpc-emu/commit/c150b3d7c38b81027105d3bcfb39e44cd643353d 

thanks!

**Comment by jsm174** [comment]
@neophob, @ecurtz: Updated in https://github.com/jsm174/wpc-emu-cs/commit/6c88580b9e114bfdbdae81844b9eb38fa0eb99db.

Pushed a new version to NuGet as well - #0.0.6.

Thanks!
